monprojet/monapp/urls.py
from django.urls import path
from .views import (
    ProductListView,
    ProductDetailView,
    HomeView,
    ProductItemListView,
    ProductItemDetailView,
    ProductAttributeListView,
    ProductAttributeDetailView,
    ConnectView,
    RegisterView,
    DisconnectView,
    ContactView,
    ProductCreateView,
    ProductUpdateView,
    ProductAttributeValueCreateView,
    CommandeListView,        
    CommandeDetailView,
    CommandeCreateView,
    CommandeUpdateView,
    CommandeDeleteView,
    FournisseurListView,      
    FournisseurDetailView,
    FournisseurCreateView,
    FournisseurUpdateView,
    FournisseurDeleteView,
    FournisseurCommandesView,
    FournisseurAddProductView
)

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("products/", ProductListView.as_view(), name="product-list"),
    path("products/<int:pk>/", ProductDetailView.as_view(), name="product-detail"),
    path("product-items/", ProductItemListView.as_view(), name="item-detail"),
    path("product-items/<int:pk>/", ProductItemDetailView.as_view(), name="product-item-detail"),
    path("product-attributes/", ProductAttributeListView.as_view(), name="product-attribute-list"),
    path("product-attributes/<int:pk>/", ProductAttributeDetailView.as_view(), name="product-attribute-detail"),
    path("login/", ConnectView.as_view(), name="login"),
    path("register/", RegisterView.as_view(), name="register"),
    path("logout/", DisconnectView.as_view(), name="logout"),
    path("contact/", ContactView, name="contact"),
    path("product/<pk>/update/", ProductUpdateView.as_view(), name="product-update"),
    path("product/add/", ProductCreateView.as_view(), name="product-add"),
    path("product-attributes/add/", ProductAttributeValueCreateView.as_view(), name="product-attribute-add"),
    path("fournisseurs/<int:pk>/commandes/", FournisseurCommandesView.as_view(), name="fournisseur-commandes"),
    path("commandes/", CommandeListView.as_view(), name="commande-list"),
    path("commandes/<int:pk>/", CommandeDetailView.as_view(), name="commande-detail"),
    path("commandes/add/", CommandeCreateView.as_view(), name="commande-add"),
    path("commandes/<int:pk>/edit/", CommandeUpdateView.as_view(), name="commande-update"),
    path("commandes/<int:pk>/delete/", CommandeDeleteView.as_view(), name="commande-delete"),
    path('fournisseur/<int:fournisseur_id>/add-product/', FournisseurAddProductView.as_view(), name='add-product-to-fournisseur'),
    path("fournisseurs/", FournisseurListView.as_view(), name="fournisseur-list"),
    path("fournisseurs/<int:pk>/", FournisseurDetailView.as_view(), name="fournisseur-detail"),
    path('fournisseur/add/', FournisseurCreateView.as_view(), name='fournisseur-add'),
    path("fournisseurs/<int:pk>/edit/", FournisseurUpdateView.as_view(), name="fournisseur-update"),
    path("fournisseurs/<int:pk>/delete/", FournisseurDeleteView.as_view(), name="fournisseur-delete"),
]

monprojet/monprojet/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("monapp/", include("monapp.urls")),
    path("admin/", admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
]

monprojet/monapp/models.py
from django.db import models
from django.utils import timezone

# Définition des états de commande
COMMANDE_STATUS = ((0, 'En préparation'), (1, 'Passée'), (2, 'Reçue'))

# Modèle pour les statuts
class Status(models.Model):
    numero = models.IntegerField()
    libelle = models.CharField(max_length=100)

    def get_libelle(self):
        return self.libelle

    def __str__(self):
        return "{0} {1}".format(self.numero, self.libelle)


# Modèle pour les produits
class Product(models.Model):
    name = models.CharField(max_length=100)
    code = models.CharField(max_length=10, null=True, blank=True, unique=True)

    def __str__(self):
        return "{0} {1}".format(self.name, self.code)


# Modèle pour les fournisseurs
class Fournisseurs(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


# Modèle pour gérer la relation entre les produits et les fournisseurs (prix, stock, etc.)
class ProductFournisseur(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    fournisseur = models.ForeignKey(Fournisseurs, on_delete=models.CASCADE)
    price_ht = models.DecimalField(
        max_digits=8, decimal_places=2, null=True, blank=True, verbose_name="Prix unitaire HT"
    )
    price_ttc = models.DecimalField(
        max_digits=8, decimal_places=2, null=True, blank=True, verbose_name="Prix unitaire TTC"
    )
    stock = models.IntegerField()
    date_creation = models.DateTimeField(default=timezone.now, verbose_name="Date création")

    class Meta:
        unique_together = ('product', 'fournisseur')

    def __str__(self):
        return f'{self.product.name} - {self.fournisseur.name}'


# Modèle pour les déclinaisons de produit (ex : couleur)
class ProductItem(models.Model):
    color = models.CharField(max_length=100)
    code = models.CharField(max_length=10, null=True, blank=True, unique=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    attributes = models.ManyToManyField("ProductAttributeValue", related_name="product_item", blank=True)

    def __str__(self):
        return "{0} {1}".format(self.color, self.code)


# Modèle pour les attributs de produit (ex : taille)
class ProductAttribute(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


# Modèle pour les valeurs des attributs de produit (ex : petite, moyenne, grande)
class ProductAttributeValue(models.Model):
    value = models.CharField(max_length=100)
    product_attribute = models.ForeignKey(ProductAttribute, verbose_name="Unité", on_delete=models.CASCADE)
    position = models.PositiveSmallIntegerField("Position", null=True, blank=True)

    def __str__(self):
        return "{0} [{1}]".format(self.value, self.product_attribute)


# Modèle pour les commandes
class Commande(models.Model):
    fournisseur = models.ForeignKey(Fournisseurs, on_delete=models.CASCADE)
    status = models.IntegerField(choices=COMMANDE_STATUS, default=0)
    date_commande = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f'Commande {self.id} - {self.fournisseur.name} - {self.get_status_display()}'

    def update_stock(self):
        if self.status == 2:  # Si la commande est reçue
            for item in self.commandeitems.all():
                product_fournisseur = ProductFournisseur.objects.get(product=item.product, fournisseur=self.fournisseur)
                product_fournisseur.stock += item.quantity
                product_fournisseur.save()


# Modèle pour les éléments de commande
class CommandeItem(models.Model):
    commande = models.ForeignKey(Commande, related_name="commandeitems", on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()

    def __str__(self):
        return f'{self.quantity}x {self.product.name}'

monprojet/monapp/views.py
from django.shortcuts import render, redirect,  get_object_or_404
from django.http import HttpResponse, Http404
from django.views.generic import *
from django.contrib.auth.views import LoginView
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.core.mail import send_mail
from .forms import ContactUsForm, ProductForm, ProductAttributeValueForm, ProductFournisseurForm, CommandeForm, ProductCreateForm, CommandeCreateForm, CommandeItemFormSet
from django.forms import BaseModelForm
from django.urls import reverse_lazy
from .models import *
# Create your views here.


class ProductItemListView(ListView):
    model = ProductItem
    template_name = "monapp/list_items.html"
    context_object_name = "productitems"
    def get_queryset(self ):
        return ProductItem.objects.all()
    def get_context_data(self, **kwargs):
        context = super(ProductItemListView, self).get_context_data(**kwargs)
        context['titremenu'] = "Liste des déclinaisons"
        return context


class ProductItemDetailView(DetailView):
    model = ProductItem
    template_name = "monapp/detail_item.html"
    context_object_name = "productitem"
    def get_context_data(self, **kwargs):
        context = super(ProductItemDetailView, self).get_context_data(**kwargs)
        context['titremenu'] = "Détail déclinaison"
        # Récupérer les attributs associés à cette déclinaison
        context['attributes'] = self.object.attributes.all()
        return context

# class ProductAttributeListView(ListView):
#     model = ProductAttribute
#     template_name = "monapp/list_product_attributes.html"
#     context_object_name = "product_attributes"

#     def get_context_data(self, **kwargs):
#         context = super(ProductAttributeListView, self).get_context_data(**kwargs)
#         context["titremenu"] = "Liste des attributs de produit"
#         return context


# class ProductAttributeDetailView(DetailView):
#     model = ProductAttribute
#     template_name = "monapp/detail_product_attribute.html"
#     context_object_name = "product_attribute"

#     def get_context_data(self, **kwargs):
#         context = super(ProductAttributeDetailView, self).get_context_data(**kwargs)
#         context["titremenu"] = "Détail attribut produit"
#         return context

class ProductAttributeDetailView(DetailView):
    model = ProductAttribute
    template_name = "monapp/detail_attribute.html"
    context_object_name = "productattribute"
    def get_context_data(self, **kwargs):
        context = super(ProductAttributeDetailView, self).get_context_data(**kwargs)
        context['titremenu'] = "Détail attribut"
        context['values']=ProductAttributeValue.objects.filter(product_attribute=self.object).order_by('position')
        return context

class FournisseurAddProductView(CreateView):
    model = ProductFournisseur
    form_class = ProductFournisseurForm
    template_name = 'monapp/add_product_to_fournisseur.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        fournisseur = get_object_or_404(Fournisseurs, pk=self.kwargs['fournisseur_id'])
        context['fournisseur'] = fournisseur
        return context

    def form_valid(self, form):
        form.instance.fournisseur = get_object_or_404(Fournisseurs, pk=self.kwargs['fournisseur_id'])
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('fournisseur-detail', kwargs={'pk': self.kwargs['fournisseur_id']})

class ProductListView(ListView):
    model = Product
    template_name = "monapp/list_products.html"
    context_object_name = "products"

    def get_queryset(self):
        query = self.request.GET.get('search')
        if query:
            return Product.objects.filter(name__icontains=query)
        return Product.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['titremenu'] = "Liste des produits"
        return context


class ProductDetailView(DetailView):
    model = Product
    template_name = "monapp/detail_product.html"
    context_object_name = "product"

    def get_context_data(self, **kwargs):
        context = super(ProductDetailView, self).get_context_data(**kwargs)
        context["titremenu"] = "Détail produit"
        return context


class HomeView(TemplateView):
    template_name = "monapp/home.html"

    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)
        context["titreh1"] = "Hello"
        context["param"] = self.kwargs.get("param", "")
        return context

    def post(self, request, **kwargs):
        return render(request, self.template_name)


class AboutView(TemplateView):
    template_name = "monapp/home.html"

    def get_context_data(self, **kwargs):
        context = super(AboutView, self).get_context_data(**kwargs)
        context["titreh1"] = "About us..."
        return context

    def post(self, request, **kwargs):
        return render(request, self.template_name)


def ContactView(request):
    titreh1 = "Contact us !"
    if request.method == "POST":
        form = ContactUsForm(request.POST)
        if form.is_valid():
            send_mail(
                subject=f'Message from {form.cleaned_data["name"] or "anonyme"} via MonProjet Contact Us form',
                message=form.cleaned_data["message"],
                from_email=form.cleaned_data["email"],
                recipient_list=["admin@monprojet.com"],
            )
    else:
        form = ContactUsForm()
    return render(request, "monapp/contact.html", {"titreh1": titreh1, "form": form})


class ConnectView(LoginView):
    template_name = "monapp/login.html"

    def post(self, request, **kwargs):
        username = request.POST.get("username", False)
        password = request.POST.get("password", False)
        user = authenticate(username=username, password=password)
        if user is not None and user.is_active:
            login(request, user)
            return render(
                request,
                "monapp/hello.html",
                {"titreh1": "hello " + username + ", you're connected"},
            )
        else:
            return render(request, "monapp/register.html")


class RegisterView(TemplateView):
    template_name = "monapp/register.html"

    def post(self, request, **kwargs):
        username = request.POST.get("username", False)
        mail = request.POST.get("mail", False)
        password = request.POST.get("password", False)
        user = User.objects.create_user(username, mail, password)
        user.save()
        if user is not None and user.is_active:
            return render(request, "monapp/login.html")
        else:
            return render(request, "monapp/register.html")


class DisconnectView(TemplateView):
    template_name = "monapp/logout.html"

    def get(self, request, **kwargs):
        logout(request)
        return render(request, self.template_name)

def ProductCreate(request):
    if request.method == 'POST':
        form = ProductForm(request.POST)
        if form.is_valid():
            product = form.save()
            return redirect('product-detail', product.id)
    else:
        form = ProductForm()
    return render(request, "monapp/new_product.html", {'form': form})

class ProductCreateView(CreateView):
    model = Product
    template_name = 'monapp/new_product.html'
    form_class = ProductCreateForm
    success_url = reverse_lazy('product-list')  

    def form_valid(self, form):
        product = form.save()

        fournisseur = form.cleaned_data['fournisseur']
        price_ht = form.cleaned_data['price_ht']
        price_ttc = form.cleaned_data['price_ttc']
        stock = form.cleaned_data['stock']
        ProductFournisseur.objects.create(
            product=product,
            fournisseur=fournisseur,
            price_ht=price_ht,
            price_ttc=price_ttc,
            stock= stock
        )

        return super().form_valid(form)

class ProductUpdateView(UpdateView):
    model = Product
    form_class=ProductForm
    template_name = "monapp/update_product.html"
    def form_valid(self, form: BaseModelForm) -> HttpResponse:
        product = form.save()
        return redirect('product-detail', product.id)
    
class ProductDeleteView(DeleteView):
    model = Product
    template_name = "monapp/delete_product.html"
    success_url = reverse_lazy('product-list')

class ProductAttributeListView(ListView):
    model = ProductAttribute
    template_name = "monapp/list_attributes.html"
    context_object_name = "productattributes"
    def get_queryset(self ):
        return ProductAttribute.objects.all()
    def get_context_data(self, **kwargs):
        context = super(ProductAttributeListView, self).get_context_data(**kwargs)
        context['titremenu'] = "Liste des attributs"
        return context
    
class ProductAttributeValueListView(ListView):
    model = ProductAttributeValue
    template_name = "monapp/list_products_attribute_value.html"
    context_object_name = "products_attribute_value"

    def get_queryset(self):
        # Surcouche pour filtrer les résultats en fonction de la recherche
        # Récupérer le terme de recherche depuis la requête GET
        query = self.request.GET.get("search")
        if query:
            # Filtre les produits par nom (insensible à la casse)
            return ProductAttributeValue.objects.filter(value__icontains=query)
        # Si aucun terme de recherche, retourner tous les produits
        return ProductAttributeValue.objects.all()

    def get_context_data(self, **kwargs):
        context = super(ProductAttributeValueListView, self).get_context_data(**kwargs)
        context["titremenu"] = "Liste des attributs value"
        return context
    
class ProductAttributeValueCreateView(CreateView):
    model = ProductAttributeValue

monprojet/monapp/templates/monapp/add_product_to_fournisseur.html
{% extends 'monapp/base.html' %}
{% block title %}Ajouter un produit au fournisseur{% endblock %}
{% block contenu %}
<h2>Ajouter un produit pour {{ fournisseur.name }}</h2>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Ajouter le produit</button>
</form>

<a href="{% url 'fournisseur-detail' fournisseur.id %}">Retour au fournisseur</a>
{% endblock %}

monprojet/monapp/templates/monapp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="fr">
  <head>
    <meta charset="utf-8" />
    <title>
      {% block title %}
      {% endblock %}
    </title>
    {% block styles %}
      <link rel="stylesheet" href="{% static 'styles.css' %}" />
      <link rel="stylesheet" href="{% static 'node_modules/bootstrap/dist/css/bootstrap.min.css' %}" />
    {% endblock %}
  </head>
  <body>
    {% block nav %}
      <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4 d-flex justify-content-around">
        {% block menu %}
          <a href="{% url 'home' %}">Accueil</a>
          <a href="{% url 'product-list' %}">Produits</a>
          <a href="{% url 'product-add' %}">Créer un nouveau produit</a>
          <a href="{% url 'product-attribute-list' %}">Attributs de produit</a>
          <a href="{% url 'commande-list' %}">Commandes</a>
          <a href="{% url 'commande-add' %}">Créer une nouvelle commande</a> 
          <a href="{% url 'fournisseur-list' %}">Fournisseurs</a>
          <a href="{% url 'fournisseur-add' %}">Créer un nouveau fournisseur</a>  
          <a href="{% url 'contact' %}">Contact</a>

          {% if user.is_authenticated %}
            <a href="{% url 'logout' %}">Déconnexion</a>
          {% else %}
            <a href="{% url 'login' %}">Connexion</a>
            <a href="{% url 'register' %}">Inscription</a>
          {% endif %}
        {% endblock %}
      </nav>
    {% endblock %}
    
    <main role="main" class="container top-pushed">
      <div class="jumbotron">
        {% block contenu %}
        {% endblock %}
      </div>
    </main>

    <footer class="footer">
      <div class="container">
        <p>
          &copy; Copyright{% now 'Y' %} by Titof Production Copyright (c)
        </p>
      </div>
    </footer>
  </body>
</html>

monprojet/monapp/templates/monapp/commande_form.html
{% extends 'base.html' %}

{% block content %}
  <h1>Modifier Commande</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <h2>Produits dans la commande :</h2>
    <ul>
      {% for item in commande_items %}
        <li>
          <label for="product_{{ item.id }}">Produit</label>
          <select name="product_{{ item.id }}">
            {% for product in produits %}
              <option value="{{ product.id }}" {% if item.product.id == product.id %}selected{% endif %}>{{ product.name }}</option>
            {% endfor %}
          </select>
          <label for="quantity_{{ item.id }}">Quantité</label>
          <input type="number" name="quantity_{{ item.id }}" value="{{ item.quantity }}">
        </li>
      {% endfor %}
    </ul>
    <button type="submit">Enregistrer</button>
  </form>
{% endblock %}

monprojet/monapp/templates/monapp/commande_list.html
{% extends 'monapp/base.html' %}
{% block contenu %}
  <h1>Liste des commandes</h1>
  <ul>
    {% for commande in commandes %}
      <li>{{ commande.id }} - {{ commande.date_commande }} - {{ commande.client }}</li> 
    {% empty %}
      <li>Aucune commande disponible.</li>
    {% endfor %}
  </ul>
{% endblock %}

monprojet/monapp/templates/monapp/detail_product_item.html
{% extends 'monapp/base.html' %}
{% block title %}
  Détail déclinaison produit
{% endblock %}
{% block contenu %}
  <h2>{{ titremenu }}</h2>
  <ul>
    <li>Couleur : {{ product_item.color }}</li>
    <li>Code : {{ product_item.code }}</li>
    <li>Produit : {{ product_item.product.name }}</li>
  </ul>
  <a href="{% url 'product-item-list' %}">Retour à la liste des déclinaisons de produit</a>
  <a href="{% url 'product-update' product.id %}">modifier</a>
{% endblock %}

monprojet/monapp/templates/monapp/home.html
{% extends 'monapp/base.html' %}
{% block contenu %}
  <h1>{{ titreh1 }} {{ param }}</h1>
{% endblock %}

monprojet/monapp/templates/monapp/list_attributes.html
{% extends 'monapp/base.html' %}
{% block contenu %}
<table class="table">
<thead>
<th>Nom</th>
<th>Valeurs</th>
<th>Position</th>
</thead>
<tbody>
{% for attribute in productattributes %}
<tr>
<td>{{ attribute.name}}</td>
<td>
{% for value in attribute.productattributevalue_set.all %}
<p>{{ value.value }}</p>
{% empty %}
<p>Aucune valeur</p>
{% endfor %}
</td>
<td>
{% for value in attribute.productattributevalue_set.all %}
<p>{{ value.position }}</p>
{% empty %}
<p>Aucune valeur</p>
{% endfor %}
</td>
<td>
{% comment %} <a href="{% url 'attribute-detail' attribute.id %}" class="btn btn-primary mt-2">Détails</a>
<a href="{% url 'attribute-update' attribute.id %}" class="btn btn-warning mt-2">Modifier</a>
<a href="{% url 'attribute-delete' attribute.id %}" class="btn btn-danger mt-2">Supprimer</a> {% endcomment %}
</td>
</tr>
{% endfor %}
<!-- Barre de recherche -->
<p class="lead mb-3 ml-0">Rechercher un élément...</p>
<form method="GET" action="">
<input class="form-control" type="text" name="search" placeholder="Tapez ici votre recherche"
value="{{ request.GET.search }}">
<button type="submit" class="btn btn-success mt-2">Rechercher</button>
</form>
</tbody>
</table>
{% endblock %}

monprojet/monapp/templates/monapp/list_items.html
{% extends 'monapp/base.html' %}
{% block contenu %}
<table class="table">
<thead>
<th>Code</th>
<th>Produit</th>
<th>Attributs associés</th>
<th>Actions</th>
</thead>
<tbody>
    <!-- Barre de recherche -->
    <p class="lead mb-3 ml-0">Rechercher un élément...</p>
    <form method="GET" action="">
        <input class="form-control" type="text" name="search" placeholder="Tapez ici votre recherche"
        value="{{ request.GET.search }}">
        <button type="submit" class="btn btn-success mt-2">Rechercher</button>
    </form>
    
    {% for item in productitems %}
    <tr>
        <td>{{ item.code }}</td>
        <td>{{ item.product.name }}</td>
        <td>
            {% for attribute in item.attributes.all %}
            <p>{{ attribute.product_attribute.name }} : {{ attribute.value }}</p>
            {% empty %}
            <p>Aucune valeur</p>
            {% endfor %}
        </td>
        <td>
            <a href="{% url 'item-detail' item.id %}" class="btn btn-primary mt-2">Détails</a>
            <a href="{% url 'item-update' item.id %}" class="btn btn-warning mt-2">Modifier</a>
            <a href="{% url 'item-delete' item.id %}" class="btn btn-danger mt-2">Supprimer</a>
        </td>
    </tr>
    {% empty %}
    <tr>
        <td colspan="4">Aucun produit trouvé.</td>
    </tr>
    {% endfor %}
</tbody>
</table>
{% endblock %}

monprojet/monapp/templates/monapp/list_product_items.html
{% extends 'monapp/base.html' %}
{% block title %}
  Liste des déclinaisons de produit
{% endblock %}
{% block contenu %}
  <h2>{{ titremenu }}</h2>
  <table class="table">
    <thead>
      <th>Couleur</th>
      <th>Code</th>
      <th>Produit</th>
    </thead>
    <tbody>
      {% for item in product_items %}
        <tr>
          <td>
            <a href="{% url 'product-item-detail' item.id %}">{{ item.color }}</a>
          </td>
          <td>{{ item.code }}</td>
          <td>{{ item.product.name }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

monprojet/monapp/templates/monapp/login.html
{% extends 'monapp/base.html' %}

{% block title %}
  Mon application DJANGO
{% endblock %}

{% block contenu %}
  <div class="align-center col-8 offset-2">
    <p class="lead mb-3 ml-0">Se connecter</p>
    <hr />
    <form method="POST" action="{% url 'login' %}" autocomplete="off">
      {% csrf_token %}
      <div class="form-group mb-3">
        <label>Identifiant</label>
        <input class="form-control" type="text" name="username" placeholder="Utilisateur" />
        <label>Mot de Passe</label>
        <input class="form-control" type="password" name="password" placeholder="Mot de passe" />
      </div>
      <button type="submit" class="btn btn-success mt-2">Se connecter</button>
    </form>
  </div>
{% endblock %}

monprojet/monapp/templates/monapp/logout.html
{% extends 'monapp/base.html' %}

{% block title %}
  Mon application DJANGO
{% endblock %}

{% block contenu %}
  <div class="align-center col-8 offset-2">
    <p class="lead mb-3 ml-0">Se déconnecter</p>
    <hr />
    <form method="POST" action="{% url 'home' %}" autocomplete="off">
      {% csrf_token %}
      <div class="form-group mb-3">
        <label>Vous avez été déconnecté.</label>
      </div>
    </form>
  </div>
{% endblock %}

monprojet/monapp/templates/monapp/new_commande.html
{% extends 'monapp/base.html' %}
{% block title %}Créer une Commande{% endblock %}
{% block contenu %}
<h2>Créer une Commande</h2>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    
    <h3>Produits à ajouter</h3>
    <table>
        <thead>
            <tr>
                <th>Produit</th>
                <th>Quantité</th>
            </tr>
        </thead>
        <tbody>
            {% for form in commande_items %}
                <tr>
                    <td>{{ form.product }}</td>
                    <td>{{ form.quantity }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <button type="submit" class="btn btn-primary">Créer Commande</button>
</form>

<a href="{% url 'commande-list' %}">Retour à la liste des commandes</a>

{% endblock %}

monprojet/monapp/templates/monapp/new_product.html
{% extends 'monapp/base.html' %}
{% block contenu %}
<h1> Création d'un nouveau produit </h1>
<form action="" method="post" novalidate>
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class="btn btn-success mt-2">Créer</button>
</form>
{% endblock %}

monprojet/monapp/templates/monapp/update_commande.html
{% extends 'monapp/base.html' %}
{% block title %}Modifier la Commande{% endblock %}
{% block contenu %}
<h2>Modifier la Commande #{{ commande.id }}</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Sauvegarder</button>
</form>
<a href="{% url 'commande-list' %}">Retour à la liste des commandes</a>
{% endblock %}